Repository NOVA-MJU/MJS_BACKEND, pull requests merged in 2025-02, with the labels that each got.

#22 fix: build.gradle mysql
  build.gradle
Labels: 🐞 Bug

#24 [fetch] 식단 api 실제 response에 맞게 수정
  src/main/resources/static/openapi.json
Labels: 📬 API, 📃 Docs

#29 로그인, 회원 가입, 회원 정보 조회, 수정, 삭제 기능 등을 제공합니다.
  .idea/misc.xml
  build.gradle
  src/main/java/nova/mjs/member/Member.java
  src/main/java/nova/mjs/member/MemberController.java
  src/main/java/nova/mjs/member/MemberDTO.java
  src/main/java/nova/mjs/member/MemberRepository.java
  src/main/java/nova/mjs/member/MemberService.java
  src/main/java/nova/mjs/member/exception/DuplicateEmailException.java
  src/main/java/nova/mjs/member/exception/MemberException.java
  src/main/java/nova/mjs/member/exception/MemberNotFoundException.java
  src/main/java/nova/mjs/member/exception/PasswordIsInvalidException.java
  src/main/java/nova/mjs/mypage/controller/MyPageController.java
  src/main/java/nova/mjs/mypage/dto/UserProfileDTO.java
  src/main/java/nova/mjs/mypage/dto/UserProfileRequest.java
  src/main/java/nova/mjs/mypage/entity/User.java
  src/main/java/nova/mjs/mypage/exception/UserNotFoundException.java
  src/main/java/nova/mjs/mypage/repository/UserRepository.java
  src/main/java/nova/mjs/mypage/service/MyPageService.java
  src/main/java/nova/mjs/util/exception/ErrorCode.java
  src/main/java/nova/mjs/util/exception/request/RequestException.java
  src/main/resources/static/openapi.json
Labels: 💎 Feature, 📬 API, 📃 Docs, 📎 medium

#32 Update SecurityConfig.java
  src/main/java/nova/mjs/util/security/SecurityConfig.java
Labels: 🐞 Bug

#17 Add notice & notice crawling modify
  .idea/modules.xml
  src/main/java/nova/mjs/notice/controller/NoticeController.java
  src/main/java/nova/mjs/notice/dto/NoticeResponseDto.java
  src/main/java/nova/mjs/notice/entity/Notice.java
  src/main/java/nova/mjs/notice/exception/NoticeDatabaseException.java
  src/main/java/nova/mjs/notice/exception/NoticeException.java
  src/main/java/nova/mjs/notice/exception/NoticeNotFoundExcetion.java
  src/main/java/nova/mjs/notice/repository/NoticeRepository.java
  src/main/java/nova/mjs/notice/service/NoticeCrawlingService.java
  src/main/java/nova/mjs/notice/service/NoticeService.java
  src/main/java/nova/mjs/util/exception/ErrorCode.java
  src/main/resources/static/openapi.json
Labels: 🔨 Refactor

#33 [FIX] config url authorization 수정
  src/main/java/nova/mjs/util/security/SecurityConfig.java
Labels: 🔨 Refactor, 📌 high

#36 [UPDATE] submodule update
  src/main/java/nova/mjs/weeklyMenu/service/WeeklyMenuService.java
Labels: 🐞 Bug

#38 Delete .idea directory
  .idea/.gitignore
  .idea/MJS_backend.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
Labels: 🔨 Refactor

#44 [FIX] 게시판 조회 시 createdAt, updatedAt 속성 추가
  src/main/java/nova/mjs/community/DTO/CommunityBoardResponse.java
Labels: 🔨 Refactor
