Repository NOVA-MJU/MJS_BACKEND, pull requests merged in 2025-03, with the labels that each got.

#45 News2
  src/main/java/nova/mjs/news/controller/NewsController.java
  src/main/java/nova/mjs/news/exception/NewsException.java
  src/main/java/nova/mjs/news/exception/NewsNotFoundException.java
  src/main/java/nova/mjs/news/repository/NewsRepository.java
  src/main/java/nova/mjs/news/service/NewsService.java
  src/main/java/nova/mjs/util/exception/ErrorCode.java
Labels: 🔨 Refactor, 📎 medium

#51 Fetch login
  src/main/java/nova/mjs/news/service/NewsService.java
  src/main/java/nova/mjs/util/exception/ErrorCode.java
  src/main/java/nova/mjs/util/jwt/JwtUtil.java
  src/main/java/nova/mjs/util/scheduler/SchedulerService.java
  src/main/java/nova/mjs/util/scheduler/exception/SchedulerCronInvalidException.java
  src/main/java/nova/mjs/util/scheduler/exception/SchedulerException.java
  src/main/java/nova/mjs/util/scheduler/exception/SchedulerTaskFailedException.java
  src/main/java/nova/mjs/util/scheduler/exception/SchedulerUnknownException.java
  src/main/java/nova/mjs/util/security/AuthDTO.java
  src/main/java/nova/mjs/util/security/FormLoginSuccessHandler.java
  src/main/java/nova/mjs/weather/WeatherService.java
  src/main/java/nova/mjs/weeklyMenu/entity/WeeklyMenu.java
  src/main/java/nova/mjs/weeklyMenu/service/WeeklyMenuService.java
Labels: 🔨 Refactor, 📎 medium

#56 [FIX] 식단 url Restful 하게 변경
  src/main/java/nova/mjs/weeklyMenu/controller/WeeklyMenuController.java
Labels: 📬 API

#57 News
  src/main/java/nova/mjs/news/controller/NewsController.java
  src/main/java/nova/mjs/news/entity/News.java
  src/main/java/nova/mjs/news/repository/NewsRepository.java
  src/main/java/nova/mjs/news/service/NewsService.java
  src/main/java/nova/mjs/util/scheduler/SchedulerService.java
Labels: 🔨 Refactor, 📎 medium

#62 [FIX] 명대신문 기사 pagination & ResponseEntity로 return 타입 변경
  src/main/java/nova/mjs/news/controller/NewsController.java
  src/main/java/nova/mjs/news/repository/NewsRepository.java
  src/main/java/nova/mjs/news/service/NewsService.java
Labels: 🔨 Refactor, 📎 medium

#71 Token reissue
  src/main/java/nova/mjs/util/jwt/AuthController.java
  src/main/java/nova/mjs/util/jwt/JwtUtil.java
  src/main/java/nova/mjs/util/security/AuthDTO.java
  src/main/java/nova/mjs/util/security/JwtAuthenticationFilter.java
Labels: 💎 Feature, 🔨 Refactor, 📎 medium
